#ifndef ADC_H
#define ADC_H

#include <inttypes.h>

void init_adc(void);

void select_probe(void);
void select_pot(void);

int16_t adc_convert(void);

// Configure the ADC to convert on the next event system trigger,
// generated by TCD5.CCB
int16_t adc_convert_triggered(void);

// Callback for regularly timed user code. This will be called at a rate
// of AMP_FC_HZ (1775 Hz).
//
// signal_amp: amplitude of signal if available, or INT16_MAX otherwise
// volume: level of volume pot if available, or UINT8_MAX otherwise
extern void adc_callback(int16_t signal_amp, uint8_t volume);

#endif // ADC_H
